### ISSUE TITLE
Feature request: add library in maven central

### ISSUE THREAD

**Issue by MarsVard** [alexbbb/android-upload-service#10]
will this library be push to maven central?

**Comment by nitinhayaran** [comment]
+1

**Comment by alexbbb** [comment]
Hi everybody! I'm switching all my projects to Android Studio. Right now I've seen that it uses jCentral by default instead of Maven Central. I'm considering in migrating the entire library as an Android Studio project and to drop the actual Eclipse project. When I'm done with that, I'm considering also to add the library in jCentral, to be able to include it in your projects by simply writing a line in your gradle build file. I've found this tutorial: https://www.virag.si/2015/01/publishing-gradle-android-library-to-jcenter/

If anyone of you has done this process before or has some knowledge about it and wants to give me some hints, I would really appreciate that :)

**Comment by alexbbb** [comment]
You can use JitPack.io to have gradle and maven dependency management support: https://jitpack.io/#alexbbb/android-upload-service
