### ISSUE TITLE
Use in a Service instead of Activity

### ISSUE THREAD

**Issue by peterswang** [alexbbb/android-upload-service#16]
Hi,

I'm trying to use this library from within an Android Service.  The AbstractUploadServiceReceiver.register requires Activity as parameter.  Compilation fails with incompatible types between Service and Activity.

I've seen sample code on the web which registers broadcast receiver in an extended Service class.  Can the same be done in this library?

Thanks,
Peter

**Comment by alexbbb** [comment]
I've refactored the AbstractUploadServiceReceiver to get Context instead of Activity: https://github.com/alexbbb/android-upload-service/commit/313ece8bc032694e0cd70bd70ece4f8d8553e8cc

Please update the library adn let me know if it works

**Comment by peterswang** [comment]
That resolved the issue.  Thanks so much for the quick fix.

BTW, from the code, it seems to handle wireless connection break by reporting an error and terminates the upload?

**Comment by alexbbb** [comment]
@peterswang glad that the issue is solved. 
What do you mean with: "it seems to handle wireless connection break by reporting an error and terminates the upload"

**Comment by peterswang** [comment]
I didn't see code that would resume the file transfer at the point of break, if connection terminated prematurely before a file completes transfer.  Such feature is necessary for transferring large files, especially when the transmission condition can change quickly.  Large files may never complete the transfers.

**Comment by alexbbb** [comment]
@peterswang resume upload is not supported by the library at the moment, but it's not a simple thing because it depends also by the server-side. 
Network connectivity change handling is purposely left to the app that uses the library, because I decided to let the developer choose what to do in case of upload error is his app.

However, if you have some ideas on how to handle either resume upload and network connectivity change automatically in the library and you want to share some code, I'll be glad to help you :)
