### ISSUE TITLE
download

### ISSUE THREAD

**Issue by MarsVard** [alexbbb/android-upload-service#20]
I have copied some classes and reversed them to add downloading capabilities to the library, should I create a branch and request merge?
Or do you think it's not worth merging into this library?

**Comment by alexbbb** [comment]
So you have implemented download capabilities with notification center progress indication, right?

**Comment by MarsVard** [comment]
Yes! almost exactly as you did with uploads, but I based my changes on my own fork I had done sometime ago. I did pull your latest changes. before adding the download capabilities. adding the download capabilites to a clean fork would not be a problem.

**Comment by alexbbb** [comment]
In this case I think the best would be to create a separate project, dedicated only to download, called for example android-download-service, so it's smaller, less complex and so easier to maintain, and completely independent from the upload service. If someone needs to make an app which has to manage both upload and download, he will include both libraries. Otherwise only one of the two, without adding extra features that he's not going to use anyway.
I'm curious to see your code to see how you have implemented it :)
