### ISSUE TITLE
Retry and codes issue

### ISSUE THREAD

**Issue by ravenet** [alexbbb/android-upload-service#30]
Hi,

It is an excellent library, and however there are few bugs.
1. when we upload a few files, it does not notified failed images to user
2. there is no retry logic to make sure files have been transferred.
3. byte reading logic is not correct. it is sending more empty bytes instead of remaining bytes when buffer size less than remaining data.

I hope that It could help to improve it and excellent job again.

Thanks

**Comment by alexbbb** [comment]
@ravenet thank you for your feedback
Points 1 and 2 are essentially the same feature request. Upload error handling and retrying are up to you. The library does not implement an automatic retry logic, but you can add it in your application. I'll give you some hints on how you can do it. Before you start the upload request, save a reference to the object you pass to the UploadService somewhere. In the broadcast receiver, when you receive an error, you can retry the upload by simply calling the UploadService again with the reference to the same upload request object.

Please explain me what do you mean with: "it is sending more empty bytes instead of remaining bytes when buffer size less than remaining data". An example with some code would be useful for me to understand and address this issue. Thank you!

**Comment by alexbbb** [comment]
@ravenet made some changes to the transfer logic and added also automatic retries. Give it a try :) 
If you have some problems, please open a new issue :)

**Comment by ravenet** [comment]
Dear Alex,

Excellent and I would to like to add features to this lib. Will you allow me to do so?

Thanks

**Comment by alexbbb** [comment]
Of course! Just fork the project, male your own additions and then send me
a pull request ;)
Il 23/lug/2015 06:37 AM, "Tea Times App" <notifications@github.com> ha
scritto:
