### ISSUE TITLE
an option to delete the original file on the phone after upload

### ISSUE THREAD

**Issue by salgado** [alexbbb/android-upload-service#40]

**Comment by alexbbb** [comment]
You have to add the following permission to your app's manifest:
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
and then you can delete the uploaded file from the AbstractUploadServiceReceiver's onCompleted method. You have to keep a reference to the uploded file paths. One simple way is to create a HashMap with uploadID's as keys and full file paths as values. I suggest you to check this post regarding file delete: http://stackoverflow.com/questions/1248292/how-to-delete-a-file-from-sd-card

However, I don't intend to implement such a feature, because it's beyond the scope of the library to make modifications on the file system. It's up to your app's specific logic to do that. Feel free to fork the project and add this feature if you need it :)
