### ISSUE TITLE
base64 format

### ISSUE THREAD

**Issue by idanbar134** [alexbbb/android-upload-service#54]
hello, 

i need to upload to my server picture in base64.

the server need 2 parameters: the base64 string, token (Body)

can i do it with this amazing library?

**Comment by alexbbb** [comment]
Currently, to make a Multipart HTTP Request, you have to add at least one file. Your server needs only two strings (the base64 encoded image and a token) so a standard POST request is all you need. Currently is not supported by Android Upload Service, but you can fork the project and extend it to add such feature.

**Comment by idanbar134** [comment]
Hi alex
I have the same issue, it will be awsome if you can ass this feature...

**Comment by alexbbb** [comment]
Just to be precise, this is not an issue, it's a feature request :) 
As I've explained in my previous post, if you are going to upload an image by converting it in base64 (which you can easily do in your Java code) and then passing it as a request parameter, that's not a Multipart HTTP Request, since there's no file to send, but only two string parameters: the base64 encoded image and the token. For that, all you need is a standard POST request and there are certainly better solutions than my library for that: Android Volley, OkHTTP, Android Async HTTP, to name a few. 

Bear in mind that uploading images in this way is bandwidth inefficient, since base64 encoding makes file sizes roughly 33% larger than their original binary representations, and that's not a good thing especially on mobile networks. You may find this article interesting: http://davidbcalhoun.com/2011/when-to-base64-encode-images-and-when-not-to/

IMHO it would be much better to use a standard HTTP/Multipart request which in your specific case has one file (the image) and one parameter (the token) and change the server-side accordingly. You will have the added benefit that your server will need less processing time and CPU than when you use base64.

If you can't change your server side or you want to do that in Android Upload Service, without using other libraries, here are some directions that you may find useful to implement what you need:
* Create a new class by extending the base `HttpUploadRequest` class. That's needed to build the request. Check how `MultipartUploadRequest` and `BinaryUploadRequest` are made to get an idea
* Create a new class by extending `MultipartUploadTask`. That will contain the logic with which the data will be transferred to the server. The task is called in the background. Check the existing tasks to get an idea of how the things works.
* Write the needed code in `UploadService` class to add support for your newly created classes
