### ISSUE TITLE
suggestion: set extra data

### ISSUE THREAD

**Issue by YoungjaeKim** [alexbbb/android-upload-service#58]
I'd like to remove files after upload. For that, it would be good to put values before start the service and to get them at the handler afterwards.

**Comment by alexbbb** [comment]
In the projects where I use the library, I needed also to associate
additional data to upload requests, but instead of carrying around extra
data in and out of the service, which personally I think it's not a good
practice, I just made a class with static methods to set and retrieve
additional data based on the UploadID. Maybe you need the same thing, too.
Il 23/nov/2015 08:07 PM, "YoungjaeKim" <notifications@github.com> ha
scritto:

**Comment by YoungjaeKim** [comment]
@alexbbb  thanks for the reply. Then, how can I get UploadID before `request.startUpload();`? This could be the only one that I can treat before/after job tracking.

**Comment by alexbbb** [comment]
@YoungjaeKim you set the UploadID in the constructor of the upload request. It can be whatever string you like. Usually I use UUID4 so I'm sure every UploadID is unique. Check the example: https://github.com/alexbbb/android-upload-service#http-multipart-upload-example

**Comment by YoungjaeKim** [comment]
OMG. sorry to bother you. I missed that.
