### ISSUE TITLE
can upload  the file who's size more than 20M ?

### ISSUE THREAD

**Issue by t2314862168** [alexbbb/android-upload-service#65]
Sorry ,I can't test it because i am not familiar with php, so i wonder whether it can solved the problem

**Comment by alexbbb** [comment]
Yes, you can. The maximum limit is set on your server. Check you server docs to see how to properly set it. On Android you have 2Gb file size limit if you use Android API < 19. If you use Android API >= 19, you don't have that limit ( http://developer.android.com/reference/java/net/HttpURLConnection.html#setFixedLengthStreamingMode%28int%29 ). That's due to the use of the fixed length streaming mode, which ensures maximum compatibility with every HTTP server out there.
